version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-server
    command: ["python", "server/fl_server.py", "--address", "0.0.0.0:8080", "--rounds", "20"]
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/app/shared
      - ./server:/app/server   # ← 추가
      - ./client:/app/client   # ← 추가 (공통 모듈 import 시 필요)

  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-client-1
    command: ["python", "client/fl_client.py", "--client-id", "1", "--server-address", "server:8080"]
    environment:
      - SERVER_ADDRESS=server:8080
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client   # ← 추가

  client2:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-client-2
    command: ["python", "client/fl_client.py", "--client-id", "2", "--server-address", "server:8080"]
    environment:
      - SERVER_ADDRESS=server:8080
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client   # ← 추가

  client3:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-client-3
    command: ["python", "client/fl_client.py", "--client-id", "3", "--server-address", "server:8080"]
    environment:
      - SERVER_ADDRESS=server:8080
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client   # ← 추가

  client4:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-client-4
    command: ["python", "client/fl_client.py", "--client-id", "4", "--server-address", "server:8080"]
    environment:
      - SERVER_ADDRESS=server:8080
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client   # ← 추가

  client5:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: fl-client-5
    command: ["python", "client/fl_client.py", "--client-id", "5", "--server-address", "server:8080"]
    environment:
      - SERVER_ADDRESS=server:8080
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client   # ← 추가
